[phases.setup]
apt_pkgs = ['python3', 'gcc']

[phases.install]
cmds = [
  'python -m venv --copies /opt/venv && . /opt/venv/bin/activate && git submodule update --init --recursive && pip install -r requirements.txt'
]

[phases.start]
cmd = 'python sponsorblockcasino.py'
